### ISSUE TITLE
Error events emitted from WriteEntry[OPENFILE] are not listened to which results in uncaught exceptions

### ISSUE THREAD

**Issue by tgds** [npm/node-tar#112]
I've noticed that errors originating from the fs.open call in _write-entry.js_ on **line 187** are not caught in the promise, but result in uncaught exceptions. 

```javascript
  [OPENFILE] () {
    fs.open(this.absolute, 'r', (er, fd) => {
      if (er)
        return this.emit('error', er)
      this[ONOPENFILE](fd)
    })
  }
```

I investigated a little bit and found the culprit in _pack.js_ on line **297**:
```javascript
  [ENTRY] (job) {
    this[JOBS] += 1
    try {
      return new this[WRITEENTRYCLASS](job.path, this[ENTRYOPT](job)).on('end', _ => {
        this[JOBDONE](job)
      })
    } catch (er) {
      this.emit('error', er)
    }
  }
```

Since WriteEntry is an event emitter, we should listen to an error event instead of wrapping this in try/catch block to properly handle the errors. Correct me if I'm wrong, maybe I'm missing some nuances or side effects (I'm still a beginner in JS), but the fix should be straight forward:

````javascript
  [ENTRY] (job) {
    this[JOBS] += 1
    return new this[WRITEENTRYCLASS](job.path, this[ENTRYOPT](job)).on('end', _ => {
      this[JOBDONE](job)
    })
    .on('error', (er) => this.emit('error', er))
  }
```

Let me know your thoughts. I'm happy to send a PR if that looks fine.

**Comment by tgds** [comment]
Similar issue with the sync version as well. Here's the stack trace: 
```
Error: EBUSY: resource busy or locked, open 'C:\Users\Tomas Gajdos\AppData\Local\Google\Chrome\User Data\Default\Current Session'
    at Object.fs.openSync (fs.js:584:18)
    at WriteEntrySync.[openfile] (C:\Users\Tomas Gajdos\node_modules\tar\lib\write-entry.js:272:25)
    at WriteEntrySync.[file] (C:\Users\Tomas Gajdos\node_modules\tar\lib\write-entry.js:184:19)
    at WriteEntrySync.[process] (C:\Users\Tomas Gajdos\node_modules\tar\lib\write-entry.js:95:37)
    at WriteEntrySync.[onlstat] (C:\Users\Tomas Gajdos\node_modules\tar\lib\write-entry.js:90:18)
    at WriteEntrySync.WriteEntry (C:\Users\Tomas Gajdos\node_modules\tar\lib\write-entry.js:70:20)
    at C:\Users\Tomas Gajdos\node_modules\tar\lib\warn-mixin.js:2:26
    at WriteEntrySync (C:\Users\Tomas Gajdos\node_modules\tar\lib\write-entry.js:260:5)
    at PackSync.[entry] (C:\Users\Tomas Gajdos\node_modules\tar\lib\pack.js:300:14)
    at PackSync.[processJob] (C:\Users\Tomas Gajdos\node_modules\tar\lib\pack.js:270:28)
```

The error was caught in pack.js on line **300** and is emitted as an error event, but it is not listened to in `createFileSync` in _create.js_: 

```javascript
const createFileSync = (opt, files) => {
  const p = new Pack.Sync(opt)

  let threw = true
  let fd
  try {
    fd = fs.openSync(opt.file, 'w', opt.mode || 0o666)
    p.on('data', chunk => fs.writeSync(fd, chunk, 0, chunk.length))
    p.on('end', _ => fs.closeSync(fd))
    addFilesSync(p, files)
    threw = false
  } finally {
    if (threw)
      try { fs.closeSync(fd) } catch (er) {}
  }
}
```

**Comment by isaacs** [comment]
Ah, yeah.  Good writeup, thanks.
