### ISSUE TITLE
Can't transform packages in memory using node-tar

### ISSUE THREAD

**Issue by dscape** [npm/node-tar#14]
Just for reference, as talked about in irc.

Getting a package from the interwebz and piping it to a parser, changing its directory structure and then sending it back to the interwebz should be possible:

``` js
var request = require("request");
var tar     = require("tar");
var zlib    = require("zlib");

request
  .get("https://nodeload.github.com/dscape-testing/hello-world-flatiron-api/"+
       "tarball/master")
  .pipe(zlib.Gunzip())
  .pipe(tar.Parse())
  .on("entry", function (entry) {
    var path = entry.path && entry.path.split("/");
    if(Array.isArray(path)) {
      path[0] = "package"
      entry.path = path.join("/");
      console.log(entry.path);
    }
    return entry;
  })
  .pipe(tar.Pack({ noProprietary: true }))
  .pipe(zlib.createGzip())
  .pipe(fstream.Writer("output.tar.gz"))
```

Right now this errors out:

```
/Users/dscape/Desktop/dev/testing-tar/node_modules/tar/lib/pack.js:137
  Object.keys(entry.props).forEach(function (k) {
         ^
TypeError: Object.keys called on non-object
    at Function.keys (native)
    at Pack._process (/Users/dscape/Desktop/dev/testing-tar/node_modules/tar/lib/pack.js:137:10)
    at Pack.add (/Users/dscape/Desktop/dev/testing-tar/node_modules/tar/lib/pack.js:66:8)
    at Pack.<anonymous> (/Users/dscape/Desktop/dev/testing-tar/node_modules/tar/lib/pack.js:42:8)
    at Pack.EventEmitter.emit (events.js:93:17)
    at Parse.Stream.pipe (stream.js:112:8)
    at Parse.Reader.pipe (/Users/dscape/Desktop/dev/testing-tar/node_modules/tar/node_modules/fstream/lib/reader.js:238:32)
    at Object.<anonymous> (/Users/dscape/Desktop/dev/testing-tar/index.js:19:4)
    at Module._compile (module.js:449:26)
    at Object.Module._extensions..js (module.js:467:10)
```

Bummer :u5272:

**Comment by rmg** [comment]
This would be awesome.

**Comment by isaacs** [comment]
This can be done in 3.1, because `ReadEntry` objects can be added to a `Pack` stream.

Here's some example code:

```js
const tar = require('tar')
const Pack = tar.Pack
const Parse = tar.Parse
const fs = require('fs')

// the tarball input, creating just for the example
tar.c({
  file: 'input.tar',
  sync: true
}, ['mutate-tarball.js', 'README.md'])

// check that it has what we expect
// outputs:
// mutate-tarball.js
// README.md
tar.t({
  file: 'input.tar',
  sync: true,
  onentry: entry => console.log(entry.path)
})

// input stream can come from anywhere
const inputStream = fs.createReadStream('input.tar')

// packer
const packer = new Pack()

// parser
const parser = new Parse()
parser.on('entry', entry => {
  entry.uid = 999
  entry.uname = 'superman'
  packer.add(entry)
})
parser.on('end', _ => packer.end())

const outputStream = fs.createWriteStream('output.tar')
packer.pipe(outputStream)

inputStream.pipe(parser)

// verify on finish
outputStream.on('finish', _ => {
  const spawn = require('child_process').spawn
  spawn('tar', ['tvf', 'output.tar'], { stdio: 'inherit' })
})
```

Output:

```
$ node mutate-tarball.js
mutate-tarball.js
README.md
-rw-r--r--  0 superman 20        980 May 12 09:50 mutate-tarball.js
-rw-r--r--  0 superman 20      33485 May 12 09:42 README.md
```
