### ISSUE TITLE
Error: write after end when installing packages with npm 5.8.0 or higher

### ISSUE THREAD

**Issue by jbcpollak** [npm/node-tar#180]
Hi, I've been working with @zkat on an npm issue which _appears_ to have a root cause in node-tar. The stack trace I am seeing is the following. We have been able to reproduce this with any version of npm > 5.8.0. (we have not tested with npm 5.7.x)

```
❯ rm -rf /tmp/empty-cache && rm -rf node_modules && npx npmc install --cache /tmp/empty-cache
npx: installed 763 in 28.723s
npm notice CANARY npmc is experimental software. If you find an issue, please file it in the main npm repository, and call out that you were using npmc.
/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/minipass/index.js:81
      throw new Error('write after end')
      ^

Error: write after end
    at MiniPass.write (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/minipass/index.js:81:13)
    at ReadEntry.entry.on (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/pacote/lib/extract-stream.js:30:21)
    at ReadEntry.emit (events.js:185:15)
    at ReadEntry.emit (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/node_modules/minipass/index.js:296:25)
    at ReadEntry.[maybeEmitEnd] (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/node_modules/minipass/index.js:249:12)
    at ReadEntry.end (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/node_modules/minipass/index.js:162:27)
    at Unpack.[consumeBody] (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/lib/parse.js:291:59)
    at Unzip.emit (events.js:180:13)
    at Unzip.emit (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/node_modules/minipass/index.js:296:25)
    at Unzip.write (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/node_modules/minipass/index.js:99:17)
    at Unzip.write (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/node_modules/minizlib/index.js:284:29)
    at Unpack.write (/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/tar/lib/parse.js:307:19)
    at PassThrough.ondata (_stream_readable.js:651:20)
/Users/jpollak/.npm/_npx/99478/lib/node_modules/npmc/node_modules/minipass/index.js:81auth@0.9.7
      throw new Error('write after end')
      ^
```

**Comment by zkat** [comment]
@isaacs for context, this started happening for some people, sometimes, when working off _network_-sourced tarballs (rather than cached ones), and it's happening in the [transform callback for pacote's extract-stream](https://github.com/zkat/pacote/blob/latest/lib/extract-stream.js#L14-L37). The error was first reported when it was using PassThrough, but I changed it to use Minipass and stopped using the `.end(....data...)` format for last writes just in case, and shipped a canary for @jbcpollak to try, and it still reproed.

**Comment by jbcpollak** [comment]
One small clarification - for us this happens _every time_ we do fresh install of our projects. We have a bootstrap script for new developers that checks out all our repos and runs `npm i` for them - it fails every time, for every developer with this error. I'm not sure if its always the same package - so I suppose it could be random, but we must have enough dependencies in our projects that it always fails.

**Comment by isaacs** [comment]
Fixed on latest pacote, in npm 6.1.

**Comment by captainkovalsky** [comment]
This issue is reproduced on macos

**Comment by VvorkCloudTechnologies** [comment]
no such file or directory, open '/home/g3006761319ishan/vvork-website/node_modules/.staging/core-js-aaa88aee/client/library.min.js.map'

i'm face the same issue
