### ISSUE TITLE
TypeError: Cannot convert a Symbol value to a string

### ISSUE THREAD

**Issue by jreidgreer** [npm/node-tar#189]
While using the [Pacote](https://github.com/zkat/pacote) package, which uses this dependency, I am getting the following error from `lib/parse.js`: 

```
TypeError: Cannot convert a Symbol value to a string
    at Unpack.<anonymous> (zone.js/dist/zone-node.js:1688:52)
    at new Parser (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/parse.js:70:12)
    at new <anonymous> (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/warn-mixin.js:2:26)
    at new Unpack (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/unpack.js:52:5)
    at extract (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/extract.js:111:10)
    at Object.module.exports (/gulp-custom-plugin/node_modules/custom-module/node_modules/tar/lib/extract.js:38:7)
    at extractStream (/gulp-custom-plugin/node_modules/custom-module/node_modules/pacote/lib/extract-stream.js:39:1
```

The error seems to stem from [this line here](https://github.com/npm/node-tar/blob/58a8d437abccd6dc884541b8bf6554901ec592cc/lib/parse.js#L69):

```js
this.on(DONE, opt.ondone)
```

Interestingly, if I go into the `tar/lib/parse.js` module and manually replace the Symbol `DONE` with a string equivalent, `onDone`, everything works as expected. I'm not sure _where_ exactly the Symbol is being coerced, however.

**Comment by jreidgreer** [comment]
Closing this, as it's an issue with Angular's `zone.js` library.
