### ISSUE TITLE
[BUG] tar.list is throwing on empty .tar.gz

### ISSUE THREAD

**Issue by tiagonapoli** [npm/node-tar#244]
I created a empty `.tar.gz` with:
```bash
tar -czf empty.tar.gz -T /dev/null
```

Checked if the `tar` command would throw checking it:
```bash
tar -t -f empty.tar.gz
```
It did't

Then I ran the snippet:
```js
const path = require("path");
const tar = require("tar");

tar
  .list({ file: path.join(__dirname, "empty.tar.gz"), strict: true })
```

And got `TAR_BAD_ARCHIVE: Unrecognized archive format`:
```
node:6534) UnhandledPromiseRejectionWarning: Error: TAR_BAD_ARCHIVE: Unrecognized archive format
    at Object.warn (/home/tiagonapoli/Desktop/a/node_modules/tar/lib/warn-mixin.js:19:40)
    at Object.<anonymous> (/home/tiagonapoli/Desktop/a/node_modules/tar/lib/parse.js:82:14)
    at Object.emit (events.js:215:7)
    at Object.[emit] (/home/tiagonapoli/Desktop/a/node_modules/tar/lib/parse.js:286:12)
    at Object.[maybeEnd] (/home/tiagonapoli/Desktop/a/node_modules/tar/lib/parse.js:402:17)
    at Object.[consumeChunk] (/home/tiagonapoli/Desktop/a/node_modules/tar/lib/parse.js:434:21)
    at Unzip.<anonymous> (/home/tiagonapoli/Desktop/a/node_modules/tar/lib/parse.js:352:29)
    at Unzip.emit (events.js:215:7)
    at Unzip.emit (/home/tiagonapoli/Desktop/a/node_modules/minipass/index.js:409:25)
    at Unzip.[maybeEmitEnd] (/home/tiagonapoli/Desktop/a/node_modules/minipass/index.js:350:12)
(node:6534) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6534) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by isaacs** [comment]
Yeah, you're in strict mode, so warnings are errors.  Turn that off and it works the same.
