### ISSUE TITLE
Extract throws unhandled error if you remove error handler after the first error

### ISSUE THREAD

**Issue by timbertson** [npm/node-tar#47]
So this is a little weird. Basically, I'm attaching an error handler to a tar `Extract` stream. If I attach it and leave it forever, it does what I'd expect:

```
var tar = require('tar');
var fs = require('fs');

var extract = tar.Extract({path: '/tmp'});
var errorHandler = function(e) {
    console.warn("Caught error from extract: " + e);
    setTimeout(function() { console.log("all quiet");}, 1000);
}
extract.on('error', errorHandler);

extract.write('not likely to be a tar');
extract.end();

$ node tar-test.js 
Caught error from extract: Error: invalid tar file
all quiet
```

However, if I am a good citizen and remove my error handler when it's no longer needed (I'm not just being pedantic, this is in library code which listens for various events and always makes sure to clean up after itself):

```
var tar = require('tar');
var fs = require('fs');

var extract = tar.Extract({path: '/tmp'});
var errorHandler = function(e) {
    console.warn("Caught error from extract: " + e);
    extract.removeListener('error', errorHandler);
}
extract.on('error', errorHandler);

extract.write('not likely to be a tar');
extract.end();


$ node tar-test.js 
Caught error from extract: Error: invalid tar file

stream.js:94
      throw er; // Unhandled stream error in pipe.
            ^
Error: invalid tar file
    at Extract.Parse._startEntry (/home/tim/dev/oni/stratifiedjs/node_modules/tar/lib/parse.js:145:13)
    at Extract.Parse._process (/home/tim/dev/oni/stratifiedjs/node_modules/tar/lib/parse.js:127:12)
    at BlockStream.<anonymous> (/home/tim/dev/oni/stratifiedjs/node_modules/tar/lib/parse.js:47:8)
    at BlockStream.emit (events.js:95:17)
    at BlockStream._emitChunk (/home/tim/dev/oni/stratifiedjs/node_modules/tar/node_modules/block-stream/block-stream.js:145:10)
    at BlockStream.resume (/home/tim/dev/oni/stratifiedjs/node_modules/tar/node_modules/block-stream/block-stream.js:58:15)
    at Extract.Reader.resume (/home/tim/dev/oni/stratifiedjs/node_modules/fstream/lib/reader.js:255:34)
    at DirWriter.<anonymous> (/home/tim/dev/oni/stratifiedjs/node_modules/tar/lib/extract.js:57:8)
    at DirWriter.emit (events.js:92:17)
    at /home/tim/dev/oni/stratifiedjs/node_modules/fstream/lib/dir-writer.js:39:8
```

Notice that it handles the error, then removes the error handler, then _another error is thrown_ (which doesn't get emitted if I simply leave the error handler attached).

So I dunno, it definitely seems like a bug. Is there something I should be doing when I receive the first error to tell the stream "hope is lost, just shut down and stop erroring"? Either way, it seems pretty odd that the second error doesn't get sent to my handler, but gets raised when it's absent.

**Comment by isaacs** [comment]
No longer relevant in v3.
